### ISSUE TITLE
Incompatible types error in HtmlElementDecorator(driver) [RU]

### ISSUE THREAD

**Issue by vasidzius** [yandex-qatools/htmlelements#104]
Добрый день,

Только начал знакомиться с фреймворком. Делаю по Вашей инструкции https://github.com/yandex-qatools/htmlelements-examples/blob/master/htmlelements-junit-example/src/site/junit-example.md

В классе `MainPage` в строке `PageFactory.initElements(new HtmlElementDecorator(driver), this)`
ошибка
 
```java
Error:(25, 59) java: incompatible types: org.openqa.selenium.WebDriver cannot be converted to ru.yandex.qatools.htmlelements.pagefactory.CustomElementLocatorFactory
```
Использую Java 8, IDEA Community 15

Буду признателен, если подскажете что не так делаю. Спасибо!

UPD: работает только так: `PageFactory.initElements(new HtmlElementDecorator(new HtmlElementLocatorFactory(driver)), this);`

**Comment by lanwen** [comment]
Пожалуйста используйте stackoverflow для вопросов, особенно русских.

**Comment by vasidzius** [comment]
Done
<http://stackoverflow.com/questions/34806069/incompatible-types-error-in-htmlelementdecoratordriver>

As I understand decision to my question is using 
    new HtmlElementLocatorFactory(driver)
instead
    driver

If so, please rewrite starting guide, which would help to other novices

**Comment by emaks** [comment]
try to use
```
ru.yandex.qatools.htmlelements.loader.HtmlElementLoader.populatePageObject(this, driver)

**Comment by artkoshelev** [comment]
It would be nice if you update manual with working example =)
