### ISSUE TITLE
Make WebDriver available from HTML Elements #2

### ISSUE THREAD

**Issue by andrew-sumner** [yandex-qatools/htmlelements#107]
This is a duplicate of #56 but as that has been open for close to 2 years now I thought I'd start another.

I need to use WebDriverWait in my element but am unable to do this currently because the constructor requires a WebDriver object.

Can you _please_ implement this functionality?

I'm using 'ru.yandex.qatools.htmlelements:htmlelements-java:1.15'

**Comment by artkoshelev** [comment]
> Can you please implement this functionality?
as soon as you provide reasonable explanation for it in original issue

**Comment by dnekhayev** [comment]
What about JavascriptExecutor? I need to execute some script inside a class that derived from HtmlElement class. The class describes a block of HtmlElements and represents a control on a web page.
