### ISSUE TITLE
Accessing any web element is doing an implicit wait

### ISSUE THREAD

**Issue by andrew-sumner** [yandex-qatools/htmlelements#108]
Whenever I call a method on a WebElement field it is performing an implicit wait.  

I have not configured the application to perform implicit waits as we _always_ use explicit waits.

Recommended advice is not to mix explicit and implicit waits (see http://www.seleniumhq.org/docs/04_webdriver_advanced.jsp), we perform explicit waits using WebDriverWait when needed. 

Ideally I would like HtmlElements to respect selenium's default behavior (ie let selenium error immediately if no explicit wait configured, or if implicit wait configured then after than time has elapsed) and only perform customized wait if @Timeout annotation is set.

**Comment by andrew-sumner** [comment]
PR created

**Comment by lanwen** [comment]
This breaks behaviour that already used by almost all users of htmlelements, so if you need to set this timeout to 0, just use `-Dwebdriver.timeouts.implicitlywait=0`
