### ISSUE TITLE
Is it possible to refresh stale elements?

### ISSUE THREAD

**Issue by andrew-sumner** [yandex-qatools/htmlelements#112]
I have a search page that contains a table that gets populated with search results after the user presses the search button.  My page object wraps the rows of the search results table in an htmlElements class.  I'm getting a stale element exception when accessing the results table - as you'd expect because it was just refreshed by an ajax request.

I've worked around it by returning a new instance of the page object after performing the search but I'd rather recreate the search results field.  Is there any way to do this?

Example:
```
@FindBy(css = "[data-viewid='Table1'] .dojoxGridRow")
List<ActivityPerformanceRow> results;

...
// I'd like to be able to do something like this
results = driver.findElements(By.cssSelector("[data-viewid='Table1'] .dojoxGridRow"));
...
```

It's not a big deal if not.

**Comment by artkoshelev** [comment]
Please post your questions on stackoverflow with #htmlelements tag.
