### ISSUE TITLE
class must either be declared abstract or implement method 'getRect()' in 'WebElement'

### ISSUE THREAD

**Issue by robertgates55** [yandex-qatools/htmlelements#114]
I recently updated versions on my test framework, and my HtmlElements classes are now displaying the error:
`class 'Blah.class' must either be declared abstract or implement abstract method 'getRect()' in 'WebElement'`

I'm running latest selenium release and 1.15 of htmlelements - any ideas what's happened or how to resolve? Tests are still running fine, but my IDE (IntelliJ) is showing the class as errorring.

**Comment by artkoshelev** [comment]
Since you have no problem with compilation and runtime execution it looks like some problems within IDE.

**Comment by pazone** [comment]
There is new ```getRect``` method has been added to ```WebElement```. You can see it [here](https://github.com/SeleniumHQ/selenium/commit/f1e491e3bb6395f6ec41f43adf734fef214884b9). So, if you are using newer Selemium than 2.52 you should implement ```getRect``` or just forget it. 
@artkoshelev what is your opinion ?

**Comment by artkoshelev** [comment]
Thank you, @pazone i just missed that change when checking it in selenium codebase. I thing we should support it in the next version, so PR's are welcome =)

**Comment by artkoshelev** [comment]
fixed here https://github.com/yandex-qatools/htmlelements/pull/115

**Comment by ham1** [comment]
Is it possible to do a new release now that this issue has been fixed and merged? Or is there some way to get the latest snapshot in maven?

**Comment by artkoshelev** [comment]
Had you tried 1.16-SNAPSHOT version?

**Comment by ham1** [comment]
I've tried but unfortunately get the following: `Could not find artifact ru.yandex.qatools.htmlelements:htmlelements-java:jar:1.16-SNAPSHOT -> [Help 1]`

**Comment by artkoshelev** [comment]
As you can see It's available in [sonatype repo](https://oss.sonatype.org/#nexus-search;gav~ru.yandex.qatools.htmlelements~htmlelements-java~~~), so check your maven settings.

**Comment by ham1** [comment]
I added the following to the pom and it's working now, many thanks.
```
<repository>
  <id>oss-sonatype</id>
  <name>oss-sonatype</name>
  <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
  <snapshots>
    <enabled>true</enabled>
  </snapshots>
</repository>
```
