### ISSUE TITLE
Internal selectors return items which have been found by the absolute path

### ISSUE THREAD

**Issue by IZaiarnyi** [yandex-qatools/htmlelements#130]
htmlelements-java 1.17

### Selectors return items which have been found by the absolute path, instead of a relative path from the class
The page contains a lot of same elements that were described in this class
```java
@FindBy(xpath = "//*[@class='row dialog-item']")
public class SceneDescription extends HtmlElement implements Waiter{
    @FindBy(xpath = "//label")
    HtmlElement selectItemRadio;

    @FindBy(xpath = "//h4")
    HtmlElement displayNameTtl;

    public void selectItem(){
        waitFor(selectItemRadio).click();
    }

    public String getDisplayName(){
        return waitFor(displayNameTtl).getText();
    }
}
```
I include them in page
```java
public class DescriptionPopup extends AbstractBasePage {
    private List<SceneDescription> sceneDescriptions;

    public void printSceneDescription(){
        for(SceneDescription item: sceneDescriptions){
            System.out.println(item.getDisplayName());
	}
}
```
and initialize them in parent class
```java
public abstract class AbstractBasePage implements Waiter {
	public AbstractBasePage() {
        HtmlElementLoader.populate(this, getDriver());
    }
```
**printSceneDescription() prints the same name(first element's name) 'sceneDescriptions.size()' times, so the count of element is correct but internal elements are initialized by data from the first found element.**

**The selectItemRadio is found by absolute path and it isn't situated in our block  //*[@class='row dialog-item']"**

_The part of Html page was attached_
[partOfDom.txt](https://github.com/yandex-qatools/htmlelements/files/410998/partOfDom.txt)

**Comment by pazone** [comment]
xpath selector like `"//label"` (starts with `//`) searches elements from the root of your HTML. But if you will use `.//` prefix it will search inside your current context element. All in all it's better to use css selectors.

**Comment by IZaiarnyi** [comment]
Thank a lot
