### ISSUE TITLE
Is any chance to back to java 7 capability?

### ISSUE THREAD

**Issue by clicman** [yandex-qatools/htmlelements#137]
HI! I see what is not a lot of code pinned to java 8. Since many projects still on java 7, is it better to keep this capability?

**Comment by lanwen** [comment]
No, 1.7 is not updated anymore, and 1.9 will be soon. Test code written for 1.7 can be compiled and launched on java 1.8 without any problem so can't see any reasons to back to 1.7 in code.

Why you can't update your jdk?

**Comment by clicman** [comment]
Because I can't violate enterprise restrictions. A lot of companies stuck in near past and requires java 7 capability.
According [this](http://www.oracle.com/technetwork/java/eol-135779.html) doc jdk 7 extended support will until Jul 2022.

**Comment by lanwen** [comment]
Yep - and `Sustaining Support` is `Indefinite` :)

Most of our users feel good with 1.8 and this version simplifies a lot of code maintaining pain. 
You can use older versions of htmlelements or fork repo and made changes to your own corporate copy with only 1.7 code.

Sorry for inconvinience.

**Comment by clicman** [comment]
All OK. I'll fork the repo and will try to be in sync with original one.

16 янв. 2017 г. 8:10 PM пользователь "Merkushev Kirill" <
notifications@github.com> написал:

**Comment by lanwen** [comment]
v1.14 without java8 code. Please ping when you start, i'll put link to readme to your fork

**Comment by clicman** [comment]
Deal!

16 янв. 2017 г. 8:20 PM пользователь "Merkushev Kirill" <
notifications@github.com> написал:

**Comment by clicman** [comment]
@lanwen we were relased Java 7 version:
https://github.com/sbtqa/htmlelements/releases/tag/1.17-JAVA7
https://oss.sonatype.org/#nexus-search;quick~ru.sbtqa.htmlelements

It pending on maven cental sync. In near future it will available on central.
