### ISSUE TITLE
[feature request] add waitFor*() and assert*() functions to TypifiedElement

### ISSUE THREAD

**Issue by emaks** [yandex-qatools/htmlelements#142]
What do you think about possibility to add new functions like 
```assertVisible(), assertExist(), waitForVisible(), waitForActive() ``` etc
to TypifiedElement.class. If it's good idea I can make pull request

**Comment by artkoshelev** [comment]
I don't think bringing checks into objects itself is a good idea. There are existing [webdriver matchers](https://github.com/yandex-qatools/matchers-java/tree/master/webdriver-matchers) in nearby repo as well as [provided by selenium](https://github.com/SeleniumHQ/selenium/tree/master/java/client/src/org/openqa/selenium/lift). The good part about matchers is that you can combine, decorate and do whole bunch of fun staff with them.
