### ISSUE TITLE
Request for a v1.19

### ISSUE THREAD

**Issue by jimmykemp** [yandex-qatools/htmlelements#143]
Hello
Would there be any chance of publishing  a v1.19 of this project please?  

Our project:
- uses Selenium > 3.5.1.  So requires v1.18 for campatability.  
- uses 'webdriver.timeouts.implicitlywait' set to 0.  So cannot use v1.18 due to this  [issue](https://github.com/yandex-qatools/htmlelements/pull/141/files), fixed by @leonsabr 

To get around this [issue](https://github.com/yandex-qatools/htmlelements/pull/141/files),  we are currently using [Jitpack](https://jitpack.io/#yandex-qatools/htmlelements/master-SNAPSHOT) to build a release from the master branch.  The master branch has a fix applied, which we have been using since August 2017, via jitpack.

Our builds notify us when using snapshot versions (which is increasingly becoming a constraint), so having a published version with this issue fixed would be great.  It also appears to be the only fix applied to master since v1.18 was released.  So perhaps a low risk release ?

Thanks in advance.
Jimmy

**Comment by artkoshelev** [comment]
I have nothing against releasing new version. I'll check if i have access to CI jobs to perform release, or invite other people if not.

**Comment by jimmykemp** [comment]
Fantastic - many thanks

**Comment by artkoshelev** [comment]
It looks like CI is down :( calling for @lanwen to make the release...

**Comment by lanwen** [comment]
no more hosted CI. Should be created from scratch with travis, or done by hands locally

**Comment by eroshenkoam** [comment]
I will make it today, no problem

**Comment by jimmykemp** [comment]
Hi @eroshenkoam 
Thanks for looking to make a build.  Any idea how far away it might be ?

thanks in advance.

**Comment by eroshenkoam** [comment]
ooops :)

**Comment by eroshenkoam** [comment]
I'm working on it right now)

**Comment by eroshenkoam** [comment]
Done: https://oss.sonatype.org/#nexus-search;quick~htmlelements
