### ISSUE TITLE
Question: When html elements 1.20 with support of Selenium version 3.141.59 will be released?

### ISSUE THREAD

**Issue by YuliyaHancharenka** [yandex-qatools/htmlelements#146]

**Comment by artkoshelev** [comment]
Let's kindly ask @eroshenkoam to perform release =)

**Comment by artkoshelev** [comment]
let's shoot out to other maintainers... @lanwen maybe?

**Comment by lanwen** [comment]
This repo is deprecated and not maintained anymore, please migrate to https://github.com/qameta/atlas which is full replacement with better architecture and a lot of new cool features

**Comment by eroshenkoam** [comment]
I will release soon)

**Comment by ham1** [comment]
Thanks.

**Comment by eroshenkoam** [comment]
done

**Comment by ham1** [comment]
Thank you for that. Do you know how long it might take to get into maven central?

**Comment by ham1** [comment]
It's there now :+1:
