### ISSUE TITLE
Provide possibility for marking classes with @FindBy and @FindBys annotations

### ISSUE THREAD

**Issue by AlexanderTolmachev** [yandex-qatools/htmlelements#2]
It would be better to mark blocks with common <code>@FindBy</code> and <code>@FindBys</code> annotations instead of <code>@Block</code> annotation. So it  is needed to make  <code>@FindBy</code> and <code>@FindBys</code> annotations both class-targeted and field-targeted.

**Comment by lanwen** [comment]
Already done in #70
