### ISSUE TITLE
Add HtmlElementFactory

### ISSUE THREAD

**Issue by ilya-murzinov** [yandex-qatools/htmlelements#61]
[based on wiki](https://github.com/yandex-qatools/htmlelements/wiki/HtmlElements-2.0#%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B)

<code>
public class HtmlElementFactory {
        public static <T extends HtmlElement> newHtmlElement(SearchContext context, By by, Class<T> clazz, String name, boolean shouldCashe) {}
    }
</code>

**Comment by emaks** [comment]
what about this fuature?

**Comment by emaks** [comment]
@artkoshelev , @eroshenkoam

What about this feature? Can I make a pull request or make some architectural changes that will provide me a possibility to implement this in my project?

**Comment by artkoshelev** [comment]
@emaks can you explain the problem you want to solve?

**Comment by emaks** [comment]
I want to use locator like ```String locator = String.format("//*[@text()='%s']", value); ``` and

**Comment by artkoshelev** [comment]
@emaks that's not the problem you solving, but solution you want to see, so what's the problem?

**Comment by emaks** [comment]
@artkoshelev 
problems are in theme and localization testing. some locators use label (I know that it is bad practice but now it's the only possible solution), some locators are different per theme because they were developed without consideration of the automatization needs.  I want to create some configuration files that will contain locators for any theme(localization) and create page instances using them.

**Comment by artkoshelev** [comment]
not sure we should solve development problems in test framework. nevertheless i would suggest a few solutions for you:
  * test localization separately (e.g. check translation files alone and quick test to check if localization works at all)
  * create complex locator avoiding using labels
  * use methods not the fields for such elements calling findElement(s) inside

**Comment by emaks** [comment]
can you give me some reasons why implementation of this idea is bad practice?

**Comment by artkoshelev** [comment]
First of all, introducing such feature made your tests much more complex, so when test fails you can't say for sure where the problem is. Secondly, if you'll solve developers problems in a test framework it will became anything but test framework.
