### ISSUE TITLE
Make methods in HtmlElementDecorator protected

### ISSUE THREAD

**Issue by Actine** [yandex-qatools/htmlelements#68]
Hello,

We use Spring in our suite extensively, and therefore to inject required dependencies into our HTML elements we need to extend `HtmlElementDecorator` and use that. However, for the decorator to perform injection recursively on all elements we need to override `decorateHtmlElement()` method as well, which is currently private and decorates all sub-elements using HtmlElementDecorator instead of our sub-class (`HtmlElementDecorator`, line 115).

The workaround for us would be to copy half of `HtmlElementDecorator`'s code, however it would be much nicer if its methods like `decorateTypifiedElement`, `decorateHtmlElement`, and maybe the rest were protected so that custom behavior could be put there, or at least the `decorateHtmlElement()` would use the `this.getClass()` instance to decorate nested elements recursively.

**Comment by tmatveyeva** [comment]
Issue was fixed somewhere between time of reporting and 1.15 release, you can close it

**Comment by Actine** [comment]
Yep, fixed in 43957e41cd67a4cd1a0a11be06ebbf3ac77c93fa. Thanks for letting me know @tmatveyeva
