### ISSUE TITLE
Nested elements

### ISSUE THREAD

**Issue by emaks** [yandex-qatools/htmlelements#77]
Is there any way to initialize new wrappedElement using instance of Typified Element and some locator?
something like this:
```
import ru.yandex.qatools.htmlelements.element.Form;

public class RegisterForm extends Form {
    private TextInput emailField;

    public RegisterForm(WebElement wrappedElement) {
        super(wrappedElement);
        emailField = createNewWrappedElement(wrappedElement, '#email');
    }
}

**Comment by aik099** [comment]
There is no need to mention `emailField` in `RegisterForm` constructor. Instead you need to add `@FindBy` annotation to the `emailField` class properly DocBlock with corresponding locator.

**Comment by emaks** [comment]
@aik099 
I need the element search to be relative to the parental(like ```getWrappedElement().findElement()```), but in this case, the element search will be done relative to the whole page. Or am I wrong?

**Comment by artkoshelev** [comment]
element search will be relative to parent, that's the main idea =)

**Comment by emaks** [comment]
great, thank you for clarification, but I can't use ``` @FindBy ``` annotation in my case. I need to create some builder to get ``` wrappedElement ``` for child element in form (I have a lot of fields in form and I don't want to declare them)

**Comment by aik099** [comment]
So you want to use field on that form, but don't want to declare class property for it. Why?

**Comment by emaks** [comment]
I want to implement something like that
```
import org.openqa.selenium.WebElement;
import ru.yandex.qatools.htmlelements.element.Form;

public class RegisterForm extends Form {
    private Map<String, String> formLocators;

    public RegisterForm(WebElement wrappedElement) {
        super(wrappedElement);
    }

    public Map<String, String> getFormLocators() {
        if (formLocators == null) {
            formLocators = new HashMap<String, String>();
            formLocators.put("email", "//input[@id='email']");
            formLocators.put("password", "//input[@id='password']");
            formLocators.put("confirmPassword", "//input[@id='confirmPassword']");
        }
        return formLocators;
    }

    public boolean isFieldVisible(String field) {
        String locator = getFormLocators().get(field);
        FormElementFactory factory = new FormElementFactory();
        WebElement wrappedField = factory.get(locator);
        return wrappedField.isDisplayed();
    }
}
```

**Comment by aik099** [comment]
That isn't supported by library. It only operates on class properties with `@FindBy` annotations.

It's absolutely ok to create properties for each form field, but for large forms this might look ugly.

**Comment by emaks** [comment]
Do you have any plans to implement this?(I found some [infrormation] (https://github.com/yandex-qatools/htmlelements/wiki/HtmlElements-2.0#%D0%94%D0%B8%D0%BD%D0%B0%D0%BC%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5-%D1%81%D0%B5%D0%BB%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D1%8B) about that ) besides ``` @FindBy ``` annotation doesn't work for ``` ru.yandex.qatools.htmlelements.element.TypifiedElement ``` Can you provide example how can I do element initialization in constructor, please?

**Comment by emaks** [comment]
Could you tell me what is the reason that you don't use child elements initialization in [decorateTypifiedElement()] (https://github.com/yandex-qatools/htmlelements/blob/master/htmlelements-java/src/main/java/ru/yandex/qatools/htmlelements/loader/decorator/HtmlElementDecorator.java#L98) function like in [decorateHtmlElement()] (https://github.com/yandex-qatools/htmlelements/blob/master/htmlelements-java/src/main/java/ru/yandex/qatools/htmlelements/loader/decorator/HtmlElementDecorator.java#L115)

**Comment by aik099** [comment]
It's up to you to place `initElements` call in constructor of your elements for it's properties to be scanned.
