### ISSUE TITLE
Current version htmlelements incompatible with last version selenium(2.47)

### ISSUE THREAD

**Issue by ITtenax** [yandex-qatools/htmlelements#89]
Now WebElement class implements an interface TakesScreenshot, because according to the standard W3C WebDriver should be able to take a screenshot of a separate element, the implementation of yet, only the interface.

**Comment by artkoshelev** [comment]
Hi, @ITtenax, thank you for reporting. We'll take a look on it in next release, or you can propose corresponding changing by yourself =)

**Comment by ITtenax** [comment]
@artkoshelev, thanks for the quick response, I will try soon to make changes

**Comment by xlenz** [comment]
Oops, I thought it is a defect in webDriver 
https://github.com/SeleniumHQ/selenium/issues/1032

**Comment by ham1** [comment]
@artkoshelev I was just looking through issues, it looks like this one can be closed?

**Comment by artkoshelev** [comment]
yep, thank you
