### ISSUE TITLE
Now Wiki information - Error 404

### ISSUE THREAD

**Issue by BCR69** [yandex-qatools/htmlelements#92]
Please, fix your Wiki https://github.com/yandex-qatools/htmlelements/wiki
Thanks

**Comment by aik099** [comment]
That was probably the temporary issue from GitHub. Now all is opening fine.

**Comment by aik099** [comment]
Ah, top page opens, but all links on it lead to 404.

**Comment by BCR69** [comment]
@aik099 Yes :(

**Comment by BCR69** [comment]
@artkoshelev fix this issue please

**Comment by artkoshelev** [comment]
Since there is not match info on wiki, i've disabled it. Thank you for report :)
