### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by ham1** [yandex-qatools/htmlelements#96]
Are there plans to upgrade to Java 8? Are there reasons not to now that it's been out for over a year and Java 7 is EoL (since April 2015)?
I've started working on improving the Table class using Java 8 streams, lambdas and Optional.

**Comment by lanwen** [comment]
Java 7 library working perfectly on Java 8 env, we don't have plan to rewrite code until the maintain process for the code goes too hard. But you can propose PR with changes :) maybe it good time to upgrade
